### ISSUE TITLE
template signature endpoints accepting an additional file (add to SDK)

### ISSUE THREAD

**Issue by alexmac05** [hellosign/hellosign-python-sdk#25] opened 2017-02-13 12:21 UTC
https://faq.hellosign.com/hc/en-us/articles/115002371968-2-1-17-Release-35
API: Ability to add a file to embedded and non-embedded send from. See updated end points: template.signature_request/create_embedded_with_template & signature_request/send_with_template  

Add these to the SDK parameter list.

**Comment by jyoung488** [comment] 2019-01-09 18:39
closing - duplicate of #43

**Closed as completed by jyoung488** 2019-01-09 18:39 UTC
